import type { Metadata } from "next";
import { Nunito, Playfair_Display } from "next/font/google";
import { ThemeProvider } from "next-themes";
import StoreProvider from "@/providers/StoreProvider";
import "./globals.css";

const playfair_display = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <body
            className={`${nunito.variable} ${playfair_display.variable} antialiased`}
          >
            {children}
          </body>
        </ThemeProvider>
      </StoreProvider>
    </html>
  );
}
