import type { Metadata } from "next";
import { Nunito, Playfair_Display, Space_Grotesk } from "next/font/google";
import { ThemeProvider } from "next-themes";
import StoreProvider from "@/providers/StoreProvider";
import "./globals.css";
import QueryProvider from "@/providers/QueryClientProvider";
import { Toaster } from "@/components/ui/sonner";

const playfair_display = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const space_grotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <QueryProvider>
          <body
            className={`${nunito.variable} ${space_grotesk.variable} antialiased`}
          >
            {children}
            <Toaster />
          </body>
        </QueryProvider>
      </StoreProvider>
    </html>
  );
}
